"""empty message

Revision ID: 66287f316311
Revises: 680be15fab87
Create Date: 2020-09-05 15:51:04.243781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66287f316311'
down_revision = '680be15fab87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('type', sa.Unicode(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    # ### end Alembic commands ###
