"""empty message

Revision ID: a12e4bac23b3
Revises: 66287f316311
Create Date: 2020-09-05 17:22:20.391519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12e4bac23b3'
down_revision = '66287f316311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('path', sa.Unicode(length=128), nullable=True))
    op.add_column('post', sa.Column('type', sa.Unicode(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type')
    op.drop_column('post', 'path')
    op.drop_column('post', 'create_date')
    # ### end Alembic commands ###
