"""empty message

Revision ID: af084ecc24e6
Revises: 2d8b96906948
Create Date: 2020-09-05 13:20:05.484385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af084ecc24e6'
down_revision = '2d8b96906948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('img_path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'img_path')
    # ### end Alembic commands ###
