"""empty message

Revision ID: c44c8e29ded6
Revises: 5912d8b4ffbb
Create Date: 2020-09-05 18:44:14.070003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c44c8e29ded6'
down_revision = '5912d8b4ffbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', sa.String(length=140), nullable=True))
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', mysql.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'description')
    # ### end Alembic commands ###
